openapi: 3.0.0
info:
  version: '1'
  title: stop
  description: >-
    Alla stop som kan användas i /api/routeArticles
paths: {}

components:
  schemas:
    parameter error:
      required:
        - parameter
        - error
      properties:
        error:
          type: string
          example: stop
        description:
          type: string
          example: stop not found
    error:
      required:
        - error
        - description
      properties:
        error:
          type: string
          example: not found
        description:
          type: string
          example: object not found
        parameter_error:
          type: array
          items:
            allOf:
              - $ref: '#/components/schemas/parameter error'
