openapi: 3.0.0
info:
  version: '1'
  title: stop
  description: >-
    Alla stop som kan användas i /api/routeArticles
paths: {}

components:
  schemas:
    wikipedia:
      required:
        - title
        - pageid
        - text
      properties:

        title:
          type: string
          example: Stockholm Centralstation
        pageid:
          type: integer
          example: 62217
        text:
          type: string
          example: wikipedia article contents including images and hyperlinks

