openapi: 3.0.0
info:
  version: '1'
  title: wikiPath
  description: >-
    Data för wikiPath
paths: {}

components:
  schemas:
    page:
      required:
        - pageid
        - title
        - lat
        - lon
        - dist
      properties:
        pageid:
          type: number
          example: 825817
        title:
          type: string
          example: Stockholms centralstation
        lat:
          type: number
          example: 59.3307
        lon:
          type: number
          example: 18.0579
        dist:
          type: number
          example: 100.0
    wikiPath:
      required:
        - pages
        - stopName
        - queryLat
        - queryLon
        - departureTime
      properties:
        pages:
          type: array
          items:
            allOf:
              - $ref: '#/components/schemas/page'
        stopName:
          type: string
          example: Stockholm Centralstation
        queryLat:
          type: number
          example: 59.3307
        queryLon:
          type: number
          example: 18.0579
        departureTime:
          type: string
          example: 19:12:00